name: build
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        release: false
        install: make yasm diffutils mingw-w64-ucrt-x86_64-aom mingw-w64-ucrt-x86_64-bzip2
          mingw-w64-ucrt-x86_64-dav1d mingw-w64-ucrt-x86_64-fontconfig mingw-w64-ucrt-x86_64-freetype
          mingw-w64-ucrt-x86_64-frei0r-plugins mingw-w64-ucrt-x86_64-fribidi mingw-w64-ucrt-x86_64-gmp
          mingw-w64-ucrt-x86_64-gnutls mingw-w64-ucrt-x86_64-gsm mingw-w64-ucrt-x86_64-harfbuzz
          mingw-w64-ucrt-x86_64-lame mingw-w64-ucrt-x86_64-libass mingw-w64-ucrt-x86_64-libbluray
          mingw-w64-ucrt-x86_64-libcaca mingw-w64-ucrt-x86_64-libexif mingw-w64-ucrt-x86_64-libgme
          mingw-w64-ucrt-x86_64-libiconv mingw-w64-ucrt-x86_64-libjxl mingw-w64-ucrt-x86_64-libmodplug
          mingw-w64-ucrt-x86_64-libssh mingw-w64-ucrt-x86_64-libplacebo mingw-w64-ucrt-x86_64-librsvg
          mingw-w64-ucrt-x86_64-libsoxr mingw-w64-ucrt-x86_64-libtheora mingw-w64-ucrt-x86_64-libva
          mingw-w64-ucrt-x86_64-libvorbis mingw-w64-ucrt-x86_64-libvpx mingw-w64-ucrt-x86_64-libwebp
          mingw-w64-ucrt-x86_64-libxml2 mingw-w64-ucrt-x86_64-libvpl mingw-w64-ucrt-x86_64-openal
          mingw-w64-ucrt-x86_64-opencore-amr mingw-w64-ucrt-x86_64-openjpeg2 mingw-w64-ucrt-x86_64-opus
          mingw-w64-ucrt-x86_64-rav1e mingw-w64-ucrt-x86_64-rtmpdump mingw-w64-ucrt-x86_64-SDL2
          mingw-w64-ucrt-x86_64-speex mingw-w64-ucrt-x86_64-srt mingw-w64-ucrt-x86_64-svt-av1
          mingw-w64-ucrt-x86_64-liblc3 mingw-w64-ucrt-x86_64-vid.stab mingw-w64-ucrt-x86_64-vulkan
          mingw-w64-ucrt-x86_64-libx264 mingw-w64-ucrt-x86_64-x265 mingw-w64-ucrt-x86_64-xvidcore
          mingw-w64-ucrt-x86_64-zimg mingw-w64-ucrt-x86_64-zlib mingw-w64-ucrt-x86_64-zvbi
          mingw-w64-ucrt-x86_64-cc mingw-w64-ucrt-x86_64-autotools mingw-w64-ucrt-x86_64-pkgconf
          mingw-w64-ucrt-x86_64-dlfcn mingw-w64-ucrt-x86_64-vulkan-headers mingw-w64-ucrt-x86_64-amf-headers
          mingw-w64-ucrt-x86_64-ffnvcodec-headers
    - name: source
      shell: cmd
      run: |
        set PATH=C:\Program Files\Git\cmd;%PATH%
        if exist "C:\Program Files\Git\usr\bin\patch.exe" set PATCH=C:\Program Files\Git\usr\bin\patch.exe
        if not defined PATCH (
        echo PATCH not found
        exit /b
        )
        if not exist ffmpeg git clone -b n7.1.1 --depth 1 https://git.ffmpeg.org/ffmpeg.git
        pushd ffmpeg
            "%PATCH%" -N -p1 -i ../d1ed5c06e3edc5f2b5f3664c80121fa55b0baa95.patch
        popd
    - name: build
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        ../ffmpeg/configure --prefix=/c/ffmpeg --disable-doc --enable-network --enable-shared --disable-debug --disable-stripping --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-iconv --enable-libaom --enable-libass --enable-libbluray --enable-libcaca --enable-libdav1d --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libssh --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libzvbi --enable-openal --enable-pic --enable-postproc --enable-runtime-cpudetect --enable-swresample --enable-version3 --enable-vulkan --enable-zlib --enable-libvpl --enable-liblc3 --enable-libplacebo --enable-librav1e --enable-librsvg --enable-libsvtav1 --enable-amf --enable-nvenc
        make
        make install
    - name: main
      shell: cmd
      run: |
        set PATH=C:\ffmpeg\bin;C:\msys64\ucrt64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\7-Zip;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        mugideploy copy-dep --bin C:\ffmpeg\bin\ffmpeg.exe --dst C:\ffmpeg\bin
        7z a -y ffmpeg.7z C:\ffmpeg
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg
        path: C:\ffmpeg
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ffmpeg.7z
